package kernel

import (
        "fmt"
        "os"
        "strings"

        "github.com/sampbb1996-dot/tsr/internal/policy"
)

// Compiler compiles a KERNEL AST to TSR source code
type Compiler struct {
        file        string
        mode        string
        budget      *KBudgetStmt
        budgetAuto  bool
        commitCount int
        out         strings.Builder
        warnings    []string
        indent      int
        policyTrace string
}

func newCompiler(file string) *Compiler {
        return &Compiler{
                file: file,
                mode: "CALM",
        }
}

func (c *Compiler) writeLine(s string) {
        c.out.WriteString(strings.Repeat("  ", c.indent))
        c.out.WriteString(s)
        c.out.WriteString("\n")
}

func (c *Compiler) writeRaw(s string) {
        c.out.WriteString(s)
}

// Compile compiles a KProgram to TSR source
func (c *Compiler) Compile(prog *KProgram) (string, []string, error) {
        // First pass: extract mode, budget, and context declarations
        var contextStmt *KContextStmt
        var bodyStmts []KStmt
        for _, stmt := range prog.Stmts {
                switch s := stmt.(type) {
                case *KModeStmt:
                        c.mode = s.Mode
                case *KBudgetAutoStmt:
                        c.budgetAuto = true
                case *KBudgetStmt:
                        c.budget = s
                case *KContextStmt:
                        contextStmt = s
                default:
                        bodyStmts = append(bodyStmts, stmt)
                }
        }

        // Resolve governance via policy engine if context block is present.
        // Explicit mode/budget declarations take precedence over policy.
        var caps policy.CapabilityConfig
        if contextStmt != nil {
                ctx := policy.Context{
                        Env:   contextStmt.Env,
                        Risk:  contextStmt.Risk,
                        Actor: contextStmt.Actor,
                }
                result := policy.Evaluate(ctx)

                // Build policy trace string
                c.policyTrace = fmt.Sprintf(
                        "[policy]\nenv=%s\nrisk=%s\nactor=%s\n-> regime=%s\n-> strain={max_branch:%d, max_loop:%d, max_call_depth:%d, max_commit:%d, max_nest:%d}\n-> capabilities={file_write:%v, net:%v}",
                        contextStmt.Env, contextStmt.Risk, contextStmt.Actor,
                        result.Regime,
                        result.Strain.MaxBranch, result.Strain.MaxLoop,
                        result.Strain.MaxCallDepth, result.Strain.MaxCommit,
                        result.Strain.MaxNest,
                        result.Capabilities.FileWrite, result.Capabilities.Net,
                )

                // Apply policy result: context block always determines regime/strain/capabilities
                c.mode = result.Regime
                if !c.budgetAuto && c.budget == nil {
                        c.budget = &KBudgetStmt{
                                MaxBranch:    result.Strain.MaxBranch,
                                MaxLoop:      result.Strain.MaxLoop,
                                MaxCallDepth: result.Strain.MaxCallDepth,
                                MaxCommit:    result.Strain.MaxCommit,
                                MaxNest:      result.Strain.MaxNest,
                        }
                }
                caps = result.Capabilities
        }

        // Auto-budget: analyze body
        var budgetToEmit KBudgetStmt
        if c.budgetAuto {
                ifCount, loopCount, commitCount, maxNest := analyzeAST(bodyStmts, 1)
                budgetToEmit = KBudgetStmt{
                        MaxBranch:    ifCount + 2,
                        MaxLoop:      loopCount + 2,
                        MaxCallDepth: 50,
                        MaxCommit:    commitCount + 2,
                        MaxNest:      maxNest + 2,
                }
        } else if c.budget != nil {
                budgetToEmit = *c.budget
        } else {
                budgetToEmit = KBudgetStmt{
                        MaxBranch:    20,
                        MaxLoop:      20,
                        MaxCallDepth: 50,
                        MaxCommit:    50,
                        MaxNest:      20,
                }
        }

        // Build header
        var header strings.Builder
        header.WriteString("# Generated by KERNEL compiler\n")

        if c.mode == "READONLY" {
                c.warnings = append(c.warnings, "WARNING: mode is READONLY -- any irreversible ops will fail at runtime")
                header.WriteString("# WARNING: mode is READONLY -- irreversible ops (http_get, write_file, etc.) will fail at runtime\n")
        }

        header.WriteString(fmt.Sprintf("regime %q;\n", c.mode))
        header.WriteString(fmt.Sprintf("strain { max_branch: %d, max_loop: %d, max_call_depth: %d, max_commit: %d, max_nest: %d };\n",
                budgetToEmit.MaxBranch,
                budgetToEmit.MaxLoop,
                budgetToEmit.MaxCallDepth,
                budgetToEmit.MaxCommit,
                budgetToEmit.MaxNest,
        ))

        // Emit capability declarations derived from policy (or auto for non-policy programs)
        if contextStmt != nil {
                for _, pat := range caps.FileWrite {
                        header.WriteString(fmt.Sprintf("capability file_write %q;\n", pat))
                }
                for _, pat := range caps.Net {
                        header.WriteString(fmt.Sprintf("capability net %q;\n", pat))
                }
        }

        // Compile body
        for _, stmt := range bodyStmts {
                if err := c.compileStmt(stmt); err != nil {
                        return "", nil, err
                }
        }

        result := header.String() + c.out.String()
        return result, c.warnings, nil
}

func (c *Compiler) compileStmt(stmt KStmt) error {
        switch s := stmt.(type) {
        case *KSetStmt:
                exprStr, err := c.compileExpr(s.Value)
                if err != nil {
                        return err
                }
                c.writeLine(fmt.Sprintf("let %s = %s;", s.Name, exprStr))

        case *KSayStmt:
                exprStr, err := c.compileExpr(s.Value)
                if err != nil {
                        return err
                }
                c.writeLine(fmt.Sprintf("say(%s);", exprStr))

        case *KIfStmt:
                condStr, err := c.compileExpr(s.Condition)
                if err != nil {
                        return err
                }
                c.writeLine(fmt.Sprintf("if (%s) {", condStr))
                c.indent++
                for _, sub := range s.Consequence {
                        if err := c.compileStmt(sub); err != nil {
                                return err
                        }
                }
                c.indent--
                if len(s.Alternative) > 0 {
                        c.writeLine("} else {")
                        c.indent++
                        for _, sub := range s.Alternative {
                                if err := c.compileStmt(sub); err != nil {
                                        return err
                                }
                        }
                        c.indent--
                }
                c.writeLine("}")

        case *KWhileStmt:
                condStr, err := c.compileExpr(s.Condition)
                if err != nil {
                        return err
                }
                c.writeLine(fmt.Sprintf("while (%s) {", condStr))
                c.indent++
                for _, sub := range s.Body {
                        if err := c.compileStmt(sub); err != nil {
                                return err
                        }
                }
                c.indent--
                c.writeLine("}")

        case *KFnStmt:
                params := strings.Join(s.Params, ", ")
                c.writeLine(fmt.Sprintf("fn %s(%s) {", s.Name, params))
                c.indent++
                for _, sub := range s.Body {
                        if err := c.compileStmt(sub); err != nil {
                                return err
                        }
                }
                c.indent--
                c.writeLine("}")

        case *KReturnStmt:
                exprStr, err := c.compileExpr(s.Value)
                if err != nil {
                        return err
                }
                c.writeLine(fmt.Sprintf("return %s;", exprStr))

        case *KReadFileStmt:
                // read_file is not governed (allowed without commit)
                c.writeLine(fmt.Sprintf("let %s = read_file(%q);", s.VarName, s.Path))

        case *KWriteFileStmt:
                exprStr, err := c.compileExpr(s.Value)
                if err != nil {
                        return err
                }
                if c.mode == "CALM" {
                        label := c.nextCommitLabel()
                        c.writeLine(fmt.Sprintf("commit %q {", label))
                        c.indent++
                        c.writeLine(fmt.Sprintf("write_file(%q, %s);", s.Path, exprStr))
                        c.indent--
                        c.writeLine("}")
                } else {
                        // READONLY: emit without commit — will fail at runtime
                        c.writeLine(fmt.Sprintf("write_file(%q, %s);", s.Path, exprStr))
                }

        case *KHttpGetStmt:
                if c.mode == "CALM" {
                        // Declare variable before commit so it's accessible outside
                        c.writeLine(fmt.Sprintf("let %s = nil;", s.VarName))
                        label := c.nextCommitLabel()
                        c.writeLine(fmt.Sprintf("commit %q {", label))
                        c.indent++
                        c.writeLine(fmt.Sprintf("%s = http_get(%q);", s.VarName, s.URL))
                        c.indent--
                        c.writeLine("}")
                } else {
                        // READONLY: emit without commit — will fail at runtime
                        c.writeLine(fmt.Sprintf("let %s = http_get(%q);", s.VarName, s.URL))
                }

        case *KImportStmt:
                c.writeLine(fmt.Sprintf("import %q as %s;", s.Path, s.Alias))
        }
        return nil
}

func (c *Compiler) nextCommitLabel() string {
        c.commitCount++
        return fmt.Sprintf("KERNEL:auto:%d", c.commitCount)
}

func (c *Compiler) compileExpr(expr KExpr) (string, error) {
        switch e := expr.(type) {
        case *KNumberLit:
                return e.Raw, nil
        case *KStringLit:
                return fmt.Sprintf("%q", e.Value), nil
        case *KBoolLit:
                if e.Value {
                        return "true", nil
                }
                return "false", nil
        case *KNilLit:
                return "nil", nil
        case *KIdent:
                return e.Name, nil
        case *KListLit:
                var parts []string
                for _, elem := range e.Elements {
                        s, err := c.compileExpr(elem)
                        if err != nil {
                                return "", err
                        }
                        parts = append(parts, s)
                }
                return "[" + strings.Join(parts, ", ") + "]", nil
        case *KDictLit:
                var parts []string
                for i, key := range e.Keys {
                        val, err := c.compileExpr(e.Values[i])
                        if err != nil {
                                return "", err
                        }
                        parts = append(parts, fmt.Sprintf("%q: %s", key, val))
                }
                return "{" + strings.Join(parts, ", ") + "}", nil
        case *KBinaryExpr:
                left, err := c.compileExpr(e.Left)
                if err != nil {
                        return "", err
                }
                right, err := c.compileExpr(e.Right)
                if err != nil {
                        return "", err
                }
                return fmt.Sprintf("(%s %s %s)", left, e.Op, right), nil
        case *KUnaryExpr:
                right, err := c.compileExpr(e.Right)
                if err != nil {
                        return "", err
                }
                return fmt.Sprintf("(%s%s)", e.Op, right), nil
        case *KCallExpr:
                var args []string
                for _, arg := range e.Args {
                        s, err := c.compileExpr(arg)
                        if err != nil {
                                return "", err
                        }
                        args = append(args, s)
                }
                return fmt.Sprintf("%s(%s)", e.Callee, strings.Join(args, ", ")), nil
        }
        return "nil", nil
}

// analyzeAST counts branches, loops, irreversible ops, and max nesting depth
func analyzeAST(stmts []KStmt, depth int) (ifCount, loopCount, commitCount, maxNest int) {
        maxNest = depth
        for _, stmt := range stmts {
                switch s := stmt.(type) {
                case *KIfStmt:
                        ifCount++
                        ic, lc, cc, mn := analyzeAST(s.Consequence, depth+1)
                        ifCount += ic
                        loopCount += lc
                        commitCount += cc
                        if mn > maxNest {
                                maxNest = mn
                        }
                        if len(s.Alternative) > 0 {
                                ic2, lc2, cc2, mn2 := analyzeAST(s.Alternative, depth+1)
                                ifCount += ic2
                                loopCount += lc2
                                commitCount += cc2
                                if mn2 > maxNest {
                                        maxNest = mn2
                                }
                        }
                case *KWhileStmt:
                        loopCount++
                        ic, lc, cc, mn := analyzeAST(s.Body, depth+1)
                        ifCount += ic
                        loopCount += lc
                        commitCount += cc
                        if mn > maxNest {
                                maxNest = mn
                        }
                case *KFnStmt:
                        ic, lc, cc, mn := analyzeAST(s.Body, depth+1)
                        ifCount += ic
                        loopCount += lc
                        commitCount += cc
                        if mn > maxNest {
                                maxNest = mn
                        }
                case *KWriteFileStmt:
                        commitCount++
                case *KHttpGetStmt:
                        commitCount++
                }
        }
        return
}

// CompileFile compiles a .krn file to TSR source.
// policyTrace is non-empty when a context block was present.
func CompileFile(path string) (tsrSource string, warnings []string, policyTrace string, err error) {
        src, err := os.ReadFile(path)
        if err != nil {
                return "", nil, "", fmt.Errorf("cannot read %q: %s", path, err)
        }

        lexer := NewKLexer(string(src), path)
        tokens, err := lexer.Tokenize()
        if err != nil {
                return "", nil, "", err
        }

        parser := NewKParser(tokens, path)
        prog, err := parser.Parse()
        if err != nil {
                return "", nil, "", err
        }

        compiler := newCompiler(path)
        tsrSource, warnings, err = compiler.Compile(prog)
        if err != nil {
                return "", nil, "", err
        }

        return tsrSource, warnings, compiler.policyTrace, nil
}

// CompileSource compiles KERNEL source string to TSR source (for testing).
// policyTrace is non-empty when a context block was present.
func CompileSource(source, filename string) (string, []string, string, error) {
        lexer := NewKLexer(source, filename)
        tokens, err := lexer.Tokenize()
        if err != nil {
                return "", nil, "", err
        }

        parser := NewKParser(tokens, filename)
        prog, err := parser.Parse()
        if err != nil {
                return "", nil, "", err
        }

        compiler := newCompiler(filename)
        tsrSource, warnings, err := compiler.Compile(prog)
        if err != nil {
                return "", nil, "", err
        }
        return tsrSource, warnings, compiler.policyTrace, nil
}
